version: '3'

services:
  db:
    image: docker.io/bitnami/postgresql:15
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=gympass_db

  db_test:
    image: docker.io/bitnami/postgresql:15
    ports:
      - '5444:5432'
    environment:
      - POSTGRESQL_USERNAME=docker_test
      - POSTGRESQL_PASSWORD=docker_test
      - POSTGRESQL_DATABASE=gympass_db_test

volumes:
  postgresql_data:
    driver: local
